apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-grafana
  namespace: default
data:
  grafana.ini: "[security] \nallow_embedding = true\n[auth.anonymous] \nenabled = true \norg_role = Admin"